# Generated by Django 5.2.8 on 2025-11-17 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.CharField(max_length=20)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('to_watch', 'To Watch'), ('watched', 'Watched'), ('to_put_away', 'To Put Away')], default='to_watch', max_length=20)),
                ('rating', models.CharField(choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down'), ('none', 'No Rating')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
